name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: npm install
    - name: build the distributable
      run: npm run build
      env:
        CI: true
    - name: can be runned
      env:
        NODE_ENV: production
      run: |
        npm start &    
        last_pid=$!
        sleep  5s
        kill -KILL $last_pid
        echo "Yay! It works"
